// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gf-chat/internal/logic/admin"
	_ "gf-chat/internal/logic/adminctx"
	_ "gf-chat/internal/logic/automessage"
	_ "gf-chat/internal/logic/autorule"
	_ "gf-chat/internal/logic/chat"
	_ "gf-chat/internal/logic/chataction"
	_ "gf-chat/internal/logic/chatmanual"
	_ "gf-chat/internal/logic/chatmessage"
	_ "gf-chat/internal/logic/chatnotice"
	_ "gf-chat/internal/logic/chatrelation"
	_ "gf-chat/internal/logic/chatsession"
	_ "gf-chat/internal/logic/chatsetting"
	_ "gf-chat/internal/logic/chattransfer"
	_ "gf-chat/internal/logic/jwt"
	_ "gf-chat/internal/logic/officialmsg"
	_ "gf-chat/internal/logic/qiniu"
	_ "gf-chat/internal/logic/rest"
	_ "gf-chat/internal/logic/sms"
	_ "gf-chat/internal/logic/sso"
	_ "gf-chat/internal/logic/subscribemsg"
	_ "gf-chat/internal/logic/user"
	_ "gf-chat/internal/logic/userCtx"
)
