// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Admins is the golang structure of table admins for DAO operations like Where/Data.
type Admins struct {
	g.Meta      `orm:"table:admins, do:true"`
	Id          interface{} //
	Username    interface{} // 用户名
	Password    interface{} // 密码
	Phone       interface{} // 手机号码
	IsSuper     interface{} // 是否超级管理员
	IsReset     interface{} // 是否重置密码(0 否 1 是)
	Status      interface{} // 状态
	ApiToken    interface{} // 登陆token
	ExpireTime  *gtime.Time // token过期时间
	LastLoginAt *gtime.Time // 最后登陆时间
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
	DeletedAt   *gtime.Time // 删除时间
}
