// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// CustomerSettings is the golang structure of table customer_settings for DAO operations like Where/Data.
type CustomerSettings struct {
	g.Meta                 `orm:"table:customer_settings, do:true"`
	Id                     interface{} //
	CustomerId             interface{} //
	Module                 interface{} // 开启的后台模块,按菜单分
	MaxAdminAmount         interface{} // 可创建最大管理员数量
	MaxUserAmount          interface{} // 最大用户数量
	IsOpenSelect           interface{} // 是否开启选餐
	NextWeekCloseDay       interface{} // 下周订单截至星期几(0-6)
	NextWeekCloseTime      interface{} // 下周订单截至时间
	OrderPrepareTime       interface{} // 次日订单准备时间（订单由已提交=》准备中 那天的变化时间）
	OrderPrepareDays       interface{} // 订单准备天数
	OrderFinishTime        interface{} //
	IsOpenMpServer         interface{} // 是否开启小程序客服功能
	IsLogMpServerMessage   interface{} // 是否开启客服消息记录
	SettleDay              interface{} // 结算时间,T+几
	SettleRate             interface{} // 结算费率(千分之几)
	SettleBank             interface{} // 结算银行
	SettleAccount          interface{} // 结算银行账号
	SettleAccountName      interface{} // 结算银行账号开户名
	PaymentMethod          interface{} // 支付方式：1：微信支付
	DefaultMealCover       interface{} // 默认套餐封面
	AutoTypes              interface{} // 自动订餐可选用的套餐类型
	AddOrderType           interface{} // 加单类型：正常加单、次日加单
	MaxCloudUserAmount     interface{} // 可创建最大云数据账号数量
	WeappFooter            interface{} // 小程序首页底部说明
	ChatOpen               interface{} // 客服系统权限
	NextDayAddTime         interface{} // 次日加单时间
	IsUserFreezingStudents interface{} // 是否允许用户冻结学生
	IsUserChangeMenu       interface{} // 是否允许客户更换套餐
	IsMaintenance          interface{} // 是否开启维护模式
	IsShowAllergen         interface{} // 是否允许显示过敏源
	IsNuclein              interface{} // 小程序是否显示员工核酸结果
	IsPicture              interface{} // 小程序是否显示员工健康证
	IsAllowAutoSetting     interface{} // 小程序是否允许用户更改自动订餐（1 是 0 否）
	IsUserCancelStudents   interface{} // 是否允许用户注销学生
	IsFeedback             interface{} // 小程序是否显示反馈意见(1 是 0 否)
	FeedbackNickname       interface{} // 反馈意见回复昵称
	IsRollbackCancel       interface{} // 是否允许用户取消请假
}
