// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// CustomerChatAutoRules is the golang structure of table customer_chat_auto_rules for DAO operations like Where/Data.
type CustomerChatAutoRules struct {
	g.Meta     `orm:"table:customer_chat_auto_rules, do:true"`
	Id         interface{} //
	Name       interface{} //
	Match      interface{} //
	MatchType  interface{} //
	ReplyType  interface{} //
	MessageId  interface{} //
	IsSystem   interface{} //
	Sort       interface{} //
	IsOpen     interface{} //
	CustomerId interface{} //
	Count      interface{} //
	CreatedAt  interface{} //
	UpdatedAt  interface{} //
}
