// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Customers is the golang structure of table customers for DAO operations like Where/Data.
type Customers struct {
	g.Meta                         `orm:"table:customers, do:true"`
	Id                             interface{} //
	Name                           interface{} // 名称
	Abbreviation                   interface{} // 标识
	ContactName                    interface{} // 联系人姓名
	ContactPhone                   interface{} // 联系人电话
	DetailAddress                  interface{} // 详细地址
	Province                       interface{} // 省
	City                           interface{} // 市
	Country                        interface{} // 区域/乡镇
	Remark                         interface{} // 备注
	Status                         interface{} // 状态：10启用，20禁用
	CreatedAt                      interface{} //
	UpdatedAt                      interface{} //
	EnterpriseBusinessLicense      interface{} // 企业营业执照
	OrganizationCodeCertificate    interface{} // 组织机构代码证
	TaxRegistrationCertificate     interface{} // 税务登记证
	CombinationOfThreeCertificates interface{} // 三证合一
	ExpiryDate                     interface{} // 续约到期时间
	RenewalStatus                  interface{} // 续约状态 0:已到期 10:未续约 20:续约中 30:取消续约 40: 终止续约
	FoodBusinessLicense            interface{} // 食品经营许可证
	LegalPersonCertificate         interface{} // 法人证件
}
