// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// CustomerChatMessages is the golang structure of table customer_chat_messages for DAO operations like Where/Data.
type CustomerChatMessages struct {
	g.Meta     `orm:"table:customer_chat_messages, do:true"`
	Id         interface{} //
	UserId     interface{} //
	AdminId    interface{} //
	Type       interface{} //
	Content    interface{} //
	ReceivedAt interface{} //
	CustomerId interface{} //
	SendAt     interface{} //
	Source     interface{} //
	SessionId  interface{} //
	ReqId      interface{} //
	ReadAt     interface{} //
}
