// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// CustomerChatSessions is the golang structure of table customer_chat_sessions for DAO operations like Where/Data.
type CustomerChatSessions struct {
	g.Meta     `orm:"table:customer_chat_sessions, do:true"`
	Id         interface{} //
	UserId     interface{} //
	QueriedAt  interface{} //
	AcceptedAt interface{} //
	CanceledAt interface{} //
	BrokeAt    interface{} //
	CustomerId interface{} //
	AdminId    interface{} //
	Type       interface{} //
	Rate       interface{} //
}
