// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// CustomerKitchens is the golang structure of table customer_kitchens for DAO operations like Where/Data.
type CustomerKitchens struct {
	g.Meta     `orm:"table:customer_kitchens, do:true"`
	Id         interface{} //
	CustomerId interface{} //
	Name       interface{} // 名称
	Address    interface{} // 详细地址
	Province   interface{} //
	City       interface{} //
	Country    interface{} //
	Longitude  interface{} // 经度
	Latitude   interface{} // 维度
	CreatedAt  interface{} //
	UpdatedAt  interface{} //
}
