// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// CustomerAdmins is the golang structure of table customer_admins for DAO operations like Where/Data.
type CustomerAdmins struct {
	g.Meta           `orm:"table:customer_admins, do:true"`
	Id               interface{} //
	CustomerId       interface{} // 客户ID
	Username         interface{} // 用户名
	Password         interface{} // 密码
	Phone            interface{} // 手机号码
	Email            interface{} // 邮箱
	IsSuper          interface{} // 是否超级管理员
	IsReset          interface{} // 是否重置过密码(0 否 1 是)
	Status           interface{} // 状态
	ApiToken         interface{} // 登陆token
	ExpireTime       interface{} // token过期时间
	LastLoginAt      interface{} // 最后登陆时间
	CreatedAt        interface{} //
	UpdatedAt        interface{} //
	DeletedAt        interface{} // 删除时间
	Gates            interface{} //
	Avatar           interface{} // 头像
	Name             interface{} // 真实姓名
	IsChat           interface{} // 是否有客服权限
	IsOfficialNotice interface{} // 公众号通知
}
