// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// MealOrders is the golang structure of table meal_orders for DAO operations like Where/Data.
type MealOrders struct {
	g.Meta               `orm:"table:meal_orders, do:true"`
	Id                   interface{} //
	CustomerId           interface{} //
	UserId               interface{} // 用户id
	StudentId            interface{} // 学生id
	MealId               interface{} // 套餐id
	TermId               interface{} // 学期id
	SchoolId             interface{} // 学校id
	StudentTermBalanceId interface{} //
	DispatchDate         interface{} // 配送日期
	DispatchGradeId      interface{} // 配送年纪
	DispatchClassId      interface{} // 配送班级
	StudentName          interface{} // 学生姓名
	Status               interface{} // 状态(10:已提交,20:准备中;30:已完成;40:已取消)
	PayPrice             interface{} // 支付金额
	PayType              interface{} //
	IsBackend            interface{} // 是否后台添加订单
	IsAuto               interface{} // 是否自动产生订单
	CreatedAt            interface{} // 下单时间
	UpdatedAt            interface{} //
	PreparedAt           interface{} // 准备时间
	FinishedAt           interface{} // 完成时间
	CancelAt             interface{} // 取消时间
	CancelReason         interface{} // 取消理由
	IsCanceledByUser     interface{} // 是否为用户取消
	OrderTypeId          interface{} // 类型id
	GiftPay              interface{} // 赠送金额支付
}
