// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// RefundOrders is the golang structure of table refund_orders for DAO operations like Where/Data.
type RefundOrders struct {
	g.Meta               `orm:"table:refund_orders, do:true"`
	Id                   interface{} //
	UserId               interface{} //
	CustomerId           interface{} //
	No                   interface{} // 退款单号
	TermId               interface{} // 学期id
	SchoolId             interface{} //
	StudentId            interface{} //
	OrderTypeId          interface{} // 订餐类型
	RefundAccount        interface{} // 退款帐号
	RefundMoney          interface{} // 退款金额
	TransferFee          interface{} // 手续费
	Status               interface{} // 状态;10:已提交
	CreatedAt            interface{} // 申请时间
	UpdatedAt            interface{} //
	AgreedAt             interface{} // 同意时间
	RefundAt             interface{} // 退款时间
	CanceledAt           interface{} // 取消时间
	RejectedAt           interface{} // 拒绝时间
	RechargeId           interface{} // 充值单id
	StudentTermBalanceId interface{} // 学生学期余额id
	Reason               interface{} // 退款理由
	Remark               interface{} // 备注
	Params               interface{} // 退款回调参数
	ErrorMsg             interface{} // 批量转账失败时的错误信息
	Type                 interface{} // 退款类型,recharge:充值，addition:其他缴费
	RechargeAdditionId   interface{} // 额外充值收费id
}
