// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Schools is the golang structure of table schools for DAO operations like Where/Data.
type Schools struct {
	g.Meta        `orm:"table:schools, do:true"`
	Id            interface{} //
	CustomerId    interface{} //
	Name          interface{} //
	Longitude     interface{} //
	Latitude      interface{} //
	Phone         interface{} // 客服电话
	Province      interface{} //
	City          interface{} //
	Country       interface{} //
	DetailAddress interface{} //
	IsDisabled    interface{} // 是否禁用，禁用后前台不可见
	CreatedAt     interface{} //
	UpdatedAt     interface{} //
	KitchenId     interface{} // 关联厨房id
	Sort          interface{} //
	IsShow        interface{} // 是否删除，删除后前后台均不可见
	SchoolNo      interface{} // 学校编码
	CanChange     interface{} // 是否能更改学校(0 否 1 是)
	PaymentMethod interface{} // 支付渠道
}
