// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SmsTemplates is the golang structure of table sms_templates for DAO operations like Where/Data.
type SmsTemplates struct {
	g.Meta     `orm:"table:sms_templates, do:true"`
	Id         interface{} //
	CustomerId interface{} //
	Type       interface{} // 短信类型
	Name       interface{} // 模板名称，长度为1~30个字符
	Content    interface{} // 模板内容
	Remark     interface{} // 短信模板申请说明
	Status     interface{} // 状态;0:审核中;1:审核通过;2:审核失败
	Code       interface{} // 模板code
	Reason     interface{} // 审核失败理由
	ApprovedAt interface{} // 通过时间
	RejectedAt interface{} // 拒绝时间
	CreatedAt  interface{} //
	UpdatedAt  interface{} //
}
