// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Users is the golang structure of table users for DAO operations like Where/Data.
type Users struct {
	g.Meta       `orm:"table:users, do:true"`
	Id           interface{} //
	Unionid      interface{} //
	CustomerId   interface{} //
	Phone        interface{} //
	Nickname     interface{} //
	RegisteredAt interface{} // 绑定手机时间
	Sex          interface{} //
	CreatedAt    interface{} // 创建时间
	UpdatedAt    interface{} //
}
