// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// UserApps is the golang structure of table user_apps for DAO operations like Where/Data.
type UserApps struct {
	g.Meta        `orm:"table:user_apps, do:true"`
	Id            interface{} //
	UserId        interface{} //
	CustomerAppId interface{} //
	OpenId        interface{} //
	AuthToken     interface{} // 验证token
	Session       interface{} //
	Type          interface{} // 类型
	CreatedAt     interface{} //
	UpdatedAt     interface{} //
}
