// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// WeappSubscribeMessages is the golang structure of table weapp_subscribe_messages for DAO operations like Where/Data.
type WeappSubscribeMessages struct {
	g.Meta      `orm:"table:weapp_subscribe_messages, do:true"`
	Id          interface{} //
	TempId      interface{} //
	Example     interface{} //
	Content     interface{} //
	KeywordEnum interface{} //
	Title       interface{} //
	Type        interface{} //
	CustomerId  interface{} //
	CreatedAt   interface{} //
	UpdatedAt   interface{} //
}
