// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// AdminsDao is the data access object for table admins.
type AdminsDao struct {
	table   string        // table is the underlying table name of the DAO.
	group   string        // group is the database configuration group name of current DAO.
	columns AdminsColumns // columns contains all the column names of Table for convenient usage.
}

// AdminsColumns defines and stores column names for table admins.
type AdminsColumns struct {
	Id          string //
	Username    string // 用户名
	Password    string // 密码
	Phone       string // 手机号码
	IsSuper     string // 是否超级管理员
	IsReset     string // 是否重置密码(0 否 1 是)
	Status      string // 状态
	ApiToken    string // 登陆token
	ExpireTime  string // token过期时间
	LastLoginAt string // 最后登陆时间
	CreatedAt   string //
	UpdatedAt   string //
	DeletedAt   string // 删除时间
}

//  adminsColumns holds the columns for table admins.
var adminsColumns = AdminsColumns{
	Id:          "id",
	Username:    "username",
	Password:    "password",
	Phone:       "phone",
	IsSuper:     "is_super",
	IsReset:     "is_reset",
	Status:      "status",
	ApiToken:    "api_token",
	ExpireTime:  "expire_time",
	LastLoginAt: "last_login_at",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
}

// NewAdminsDao creates and returns a new DAO object for table data access.
func NewAdminsDao() *AdminsDao {
	return &AdminsDao{
		group:   "default",
		table:   "admins",
		columns: adminsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AdminsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *AdminsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *AdminsDao) Columns() AdminsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *AdminsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AdminsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AdminsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
