// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// StudentsDao is the data access object for table students.
type StudentsDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns StudentsColumns // columns contains all the column names of Table for convenient usage.
}

// StudentsColumns defines and stores column names for table students.
type StudentsColumns struct {
	Id                 string //
	CustomerId         string // 客户id
	UserId             string // 用户Id
	SchoolId           string // 学校id
	GradeId            string // 年纪id
	ClassId            string // 班级Id
	EatGradeId         string // 就餐年级
	EatClassId         string // 就餐班级
	Name               string // 名称
	NamePinyin         string //
	Sex                string // 性别
	CreatedAt          string //
	UpdatedAt          string //
	IsSpecificRecharge string // 开启单独充值,不受学校充值设置影响
	IsSpecificRefund   string // 开启单独退款，不受学校退款设置影响
	TypeId             string //
	IsAuto             string // 是否开启自动订餐
	IsHide             string // 是否在前台隐藏：0显示，1隐藏
	IsFreeze           string // 非选餐情况下是否不加单
	IsCancel           string // 是否注销 0否, 1是
}

//  studentsColumns holds the columns for table students.
var studentsColumns = StudentsColumns{
	Id:                 "id",
	CustomerId:         "customer_id",
	UserId:             "user_id",
	SchoolId:           "school_id",
	GradeId:            "grade_id",
	ClassId:            "class_id",
	EatGradeId:         "eat_grade_id",
	EatClassId:         "eat_class_id",
	Name:               "name",
	NamePinyin:         "name_pinyin",
	Sex:                "sex",
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
	IsSpecificRecharge: "is_specific_recharge",
	IsSpecificRefund:   "is_specific_refund",
	TypeId:             "type_id",
	IsAuto:             "is_auto",
	IsHide:             "is_hide",
	IsFreeze:           "is_freeze",
	IsCancel:           "is_cancel",
}

// NewStudentsDao creates and returns a new DAO object for table data access.
func NewStudentsDao() *StudentsDao {
	return &StudentsDao{
		group:   "default",
		table:   "students",
		columns: studentsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *StudentsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *StudentsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *StudentsDao) Columns() StudentsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *StudentsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *StudentsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *StudentsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
