// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WeappSubscribeMessagesDao is the data access object for table weapp_subscribe_messages.
type WeappSubscribeMessagesDao struct {
	table   string                        // table is the underlying table name of the DAO.
	group   string                        // group is the database configuration group name of current DAO.
	columns WeappSubscribeMessagesColumns // columns contains all the column names of Table for convenient usage.
}

// WeappSubscribeMessagesColumns defines and stores column names for table weapp_subscribe_messages.
type WeappSubscribeMessagesColumns struct {
	Id          string //
	TempId      string //
	Example     string //
	Content     string //
	KeywordEnum string //
	Title       string //
	Type        string //
	CustomerId  string //
	CreatedAt   string //
	UpdatedAt   string //
}

//  weappSubscribeMessagesColumns holds the columns for table weapp_subscribe_messages.
var weappSubscribeMessagesColumns = WeappSubscribeMessagesColumns{
	Id:          "id",
	TempId:      "temp_id",
	Example:     "example",
	Content:     "content",
	KeywordEnum: "keyword_enum",
	Title:       "title",
	Type:        "type",
	CustomerId:  "customer_id",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

// NewWeappSubscribeMessagesDao creates and returns a new DAO object for table data access.
func NewWeappSubscribeMessagesDao() *WeappSubscribeMessagesDao {
	return &WeappSubscribeMessagesDao{
		group:   "default",
		table:   "weapp_subscribe_messages",
		columns: weappSubscribeMessagesColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WeappSubscribeMessagesDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WeappSubscribeMessagesDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WeappSubscribeMessagesDao) Columns() WeappSubscribeMessagesColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WeappSubscribeMessagesDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WeappSubscribeMessagesDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WeappSubscribeMessagesDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
