// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// Customers is the golang structure for table customers.
type Customers struct {
	Id                             int       `json:"id"                             ` //
	Name                           string    `json:"name"                           ` // 名称Abbreviation                   string    `json:"abbreviation"                   ` // 标识
	CreatedAt                      time.Time `json:"createdAt"                      ` //
	UpdatedAt                      time.Time `json:"updatedAt"                      ` //
}
