// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// Customers is the golang structure for table customers.
type Customers struct {
	Id                             int       `json:"id"                             ` //
	Name                           string    `json:"name"                           ` // 名称
	Abbreviation                   string    `json:"abbreviation"                   ` // 标识
	ContactName                    string    `json:"contactName"                    ` // 联系人姓名
	ContactPhone                   string    `json:"contactPhone"                   ` // 联系人电话
	DetailAddress                  string    `json:"detailAddress"                  ` // 详细地址
	Province                       string    `json:"province"                       ` // 省
	City                           string    `json:"city"                           ` // 市
	Country                        string    `json:"country"                        ` // 区域/乡镇
	Remark                         string    `json:"remark"                         ` // 备注
	Status                         int       `json:"status"                         ` // 状态：10启用，20禁用
	CreatedAt                      time.Time `json:"createdAt"                      ` //
	UpdatedAt                      time.Time `json:"updatedAt"                      ` //
	EnterpriseBusinessLicense      string    `json:"enterpriseBusinessLicense"      ` // 企业营业执照
	OrganizationCodeCertificate    string    `json:"organizationCodeCertificate"    ` // 组织机构代码证
	TaxRegistrationCertificate     string    `json:"taxRegistrationCertificate"     ` // 税务登记证
	CombinationOfThreeCertificates string    `json:"combinationOfThreeCertificates" ` // 三证合一
	ExpiryDate                     time.Time `json:"expiryDate"                     ` // 续约到期时间
	RenewalStatus                  int       `json:"renewalStatus"                  ` // 续约状态 0:已到期 10:未续约 20:续约中 30:取消续约 40: 终止续约
	FoodBusinessLicense            string    `json:"foodBusinessLicense"            ` // 食品经营许可证
	LegalPersonCertificate         string    `json:"legalPersonCertificate"         ` // 法人证件
}
