// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// CustomerAdmins is the golang structure for table customer_admins.
type CustomerAdmins struct {
	Id               uint      `json:"id"               ` //
	CustomerId       int       `json:"customerId"       ` // 客户ID
	Username         string    `json:"username"         ` // 用户名
	Password         string    `json:"password"         ` // 密码
	CreatedAt        time.Time `json:"createdAt"        ` //
	UpdatedAt        time.Time `json:"updatedAt"        ` //
	DeletedAt        time.Time `json:"deletedAt"        ` // 删除时间
}
