// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// CustomerAdmins is the golang structure for table customer_admins.
type CustomerAdmins struct {
	Id               uint      `json:"id"               ` //
	CustomerId       int       `json:"customerId"       ` // 客户ID
	Username         string    `json:"username"         ` // 用户名
	Password         string    `json:"password"         ` // 密码
	Phone            string    `json:"phone"            ` // 手机号码
	Email            string    `json:"email"            ` // 邮箱
	IsSuper          int       `json:"isSuper"          ` // 是否超级管理员
	IsReset          int       `json:"isReset"          ` // 是否重置过密码(0 否 1 是)
	Status           int       `json:"status"           ` // 状态
	ApiToken         string    `json:"apiToken"         ` // 登陆token
	ExpireTime       time.Time `json:"expireTime"       ` // token过期时间
	LastLoginAt      time.Time `json:"lastLoginAt"      ` // 最后登陆时间
	CreatedAt        time.Time `json:"createdAt"        ` //
	UpdatedAt        time.Time `json:"updatedAt"        ` //
	DeletedAt        time.Time `json:"deletedAt"        ` // 删除时间
	Gates            string    `json:"gates"            ` //
	Avatar           string    `json:"avatar"           ` // 头像
	Name             string    `json:"name"             ` // 真实姓名
	IsChat           int       `json:"isChat"           ` // 是否有客服权限
	IsOfficialNotice int       `json:"isOfficialNotice" ` // 公众号通知
}
