// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// Users is the golang structure for table users.
type Users struct {
	Id           int       `json:"id"           ` //
	CustomerId   int       `json:"customerId"   ` //
	CreatedAt    time.Time `json:"createdAt"    ` // 创建时间
	UpdatedAt    time.Time `json:"updatedAt"    ` //
}
