// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// Users is the golang structure for table users.
type Users struct {
	Id           int       `json:"id"           ` //
	Unionid      string    `json:"unionid"      ` //
	CustomerId   int       `json:"customerId"   ` //
	Phone        string    `json:"phone"        ` //
	Nickname     string    `json:"nickname"     ` //
	RegisteredAt time.Time `json:"registeredAt" ` // 绑定手机时间
	Sex          int       `json:"sex"          ` //
	CreatedAt    time.Time `json:"createdAt"    ` // 创建时间
	UpdatedAt    time.Time `json:"updatedAt"    ` //
}
