// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: chat/v1/chat.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chat_GetOnlineUserIds_FullMethodName       = "/chat.Chat/GetOnlineUserIds"
	Chat_GetConnInfo_FullMethodName            = "/chat.Chat/GetConnInfo"
	Chat_SendMessage_FullMethodName            = "/chat.Chat/SendMessage"
	Chat_NoticeRead_FullMethodName             = "/chat.Chat/NoticeRead"
	Chat_UpdateAdminSetting_FullMethodName     = "/chat.Chat/UpdateAdminSetting"
	Chat_BroadcastWaitingUser_FullMethodName   = "/chat.Chat/BroadcastWaitingUser"
	Chat_BroadcastOnlineAdmins_FullMethodName  = "/chat.Chat/BroadcastOnlineAdmins"
	Chat_BroadcastQueueLocation_FullMethodName = "/chat.Chat/BroadcastQueueLocation"
	Chat_NoticeTransfer_FullMethodName         = "/chat.Chat/NoticeTransfer"
	Chat_NoticeUserOnline_FullMethodName       = "/chat.Chat/NoticeUserOnline"
	Chat_NoticeUserOffline_FullMethodName      = "/chat.Chat/NoticeUserOffline"
	Chat_NoticeRepeatConnect_FullMethodName    = "/chat.Chat/NoticeRepeatConnect"
)

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	GetOnlineUserIds(ctx context.Context, in *GetOnlineUserIdsRequest, opts ...grpc.CallOption) (*GetOnlineUserIdsReply, error)
	GetConnInfo(ctx context.Context, in *GetConnInfoRequest, opts ...grpc.CallOption) (*GetConnInfoReply, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*NilReply, error)
	NoticeRead(ctx context.Context, in *NoticeReadRequest, opts ...grpc.CallOption) (*NoticeReadReply, error)
	UpdateAdminSetting(ctx context.Context, in *UpdateAdminSettingRequest, opts ...grpc.CallOption) (*NilReply, error)
	BroadcastWaitingUser(ctx context.Context, in *BroadcastWaitingUserRequest, opts ...grpc.CallOption) (*NilReply, error)
	BroadcastOnlineAdmins(ctx context.Context, in *BroadcastOnlineAdminsRequest, opts ...grpc.CallOption) (*NilReply, error)
	BroadcastQueueLocation(ctx context.Context, in *BroadcastQueueLocationRequest, opts ...grpc.CallOption) (*NilReply, error)
	NoticeTransfer(ctx context.Context, in *NoticeTransferRequest, opts ...grpc.CallOption) (*NilReply, error)
	NoticeUserOnline(ctx context.Context, in *NoticeUserOnlineRequest, opts ...grpc.CallOption) (*NilReply, error)
	NoticeUserOffline(ctx context.Context, in *NoticeUserOfflineRequest, opts ...grpc.CallOption) (*NilReply, error)
	NoticeRepeatConnect(ctx context.Context, in *NoticeRepeatConnectRequest, opts ...grpc.CallOption) (*NilReply, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) GetOnlineUserIds(ctx context.Context, in *GetOnlineUserIdsRequest, opts ...grpc.CallOption) (*GetOnlineUserIdsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOnlineUserIdsReply)
	err := c.cc.Invoke(ctx, Chat_GetOnlineUserIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetConnInfo(ctx context.Context, in *GetConnInfoRequest, opts ...grpc.CallOption) (*GetConnInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnInfoReply)
	err := c.cc.Invoke(ctx, Chat_GetConnInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*NilReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NilReply)
	err := c.cc.Invoke(ctx, Chat_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) NoticeRead(ctx context.Context, in *NoticeReadRequest, opts ...grpc.CallOption) (*NoticeReadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoticeReadReply)
	err := c.cc.Invoke(ctx, Chat_NoticeRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) UpdateAdminSetting(ctx context.Context, in *UpdateAdminSettingRequest, opts ...grpc.CallOption) (*NilReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NilReply)
	err := c.cc.Invoke(ctx, Chat_UpdateAdminSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) BroadcastWaitingUser(ctx context.Context, in *BroadcastWaitingUserRequest, opts ...grpc.CallOption) (*NilReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NilReply)
	err := c.cc.Invoke(ctx, Chat_BroadcastWaitingUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) BroadcastOnlineAdmins(ctx context.Context, in *BroadcastOnlineAdminsRequest, opts ...grpc.CallOption) (*NilReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NilReply)
	err := c.cc.Invoke(ctx, Chat_BroadcastOnlineAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) BroadcastQueueLocation(ctx context.Context, in *BroadcastQueueLocationRequest, opts ...grpc.CallOption) (*NilReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NilReply)
	err := c.cc.Invoke(ctx, Chat_BroadcastQueueLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) NoticeTransfer(ctx context.Context, in *NoticeTransferRequest, opts ...grpc.CallOption) (*NilReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NilReply)
	err := c.cc.Invoke(ctx, Chat_NoticeTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) NoticeUserOnline(ctx context.Context, in *NoticeUserOnlineRequest, opts ...grpc.CallOption) (*NilReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NilReply)
	err := c.cc.Invoke(ctx, Chat_NoticeUserOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) NoticeUserOffline(ctx context.Context, in *NoticeUserOfflineRequest, opts ...grpc.CallOption) (*NilReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NilReply)
	err := c.cc.Invoke(ctx, Chat_NoticeUserOffline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) NoticeRepeatConnect(ctx context.Context, in *NoticeRepeatConnectRequest, opts ...grpc.CallOption) (*NilReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NilReply)
	err := c.cc.Invoke(ctx, Chat_NoticeRepeatConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility.
type ChatServer interface {
	GetOnlineUserIds(context.Context, *GetOnlineUserIdsRequest) (*GetOnlineUserIdsReply, error)
	GetConnInfo(context.Context, *GetConnInfoRequest) (*GetConnInfoReply, error)
	SendMessage(context.Context, *SendMessageRequest) (*NilReply, error)
	NoticeRead(context.Context, *NoticeReadRequest) (*NoticeReadReply, error)
	UpdateAdminSetting(context.Context, *UpdateAdminSettingRequest) (*NilReply, error)
	BroadcastWaitingUser(context.Context, *BroadcastWaitingUserRequest) (*NilReply, error)
	BroadcastOnlineAdmins(context.Context, *BroadcastOnlineAdminsRequest) (*NilReply, error)
	BroadcastQueueLocation(context.Context, *BroadcastQueueLocationRequest) (*NilReply, error)
	NoticeTransfer(context.Context, *NoticeTransferRequest) (*NilReply, error)
	NoticeUserOnline(context.Context, *NoticeUserOnlineRequest) (*NilReply, error)
	NoticeUserOffline(context.Context, *NoticeUserOfflineRequest) (*NilReply, error)
	NoticeRepeatConnect(context.Context, *NoticeRepeatConnectRequest) (*NilReply, error)
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServer struct{}

func (UnimplementedChatServer) GetOnlineUserIds(context.Context, *GetOnlineUserIdsRequest) (*GetOnlineUserIdsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnlineUserIds not implemented")
}
func (UnimplementedChatServer) GetConnInfo(context.Context, *GetConnInfoRequest) (*GetConnInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnInfo not implemented")
}
func (UnimplementedChatServer) SendMessage(context.Context, *SendMessageRequest) (*NilReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatServer) NoticeRead(context.Context, *NoticeReadRequest) (*NoticeReadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoticeRead not implemented")
}
func (UnimplementedChatServer) UpdateAdminSetting(context.Context, *UpdateAdminSettingRequest) (*NilReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAdminSetting not implemented")
}
func (UnimplementedChatServer) BroadcastWaitingUser(context.Context, *BroadcastWaitingUserRequest) (*NilReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastWaitingUser not implemented")
}
func (UnimplementedChatServer) BroadcastOnlineAdmins(context.Context, *BroadcastOnlineAdminsRequest) (*NilReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastOnlineAdmins not implemented")
}
func (UnimplementedChatServer) BroadcastQueueLocation(context.Context, *BroadcastQueueLocationRequest) (*NilReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastQueueLocation not implemented")
}
func (UnimplementedChatServer) NoticeTransfer(context.Context, *NoticeTransferRequest) (*NilReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoticeTransfer not implemented")
}
func (UnimplementedChatServer) NoticeUserOnline(context.Context, *NoticeUserOnlineRequest) (*NilReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoticeUserOnline not implemented")
}
func (UnimplementedChatServer) NoticeUserOffline(context.Context, *NoticeUserOfflineRequest) (*NilReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoticeUserOffline not implemented")
}
func (UnimplementedChatServer) NoticeRepeatConnect(context.Context, *NoticeRepeatConnectRequest) (*NilReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoticeRepeatConnect not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}
func (UnimplementedChatServer) testEmbeddedByValue()              {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	// If the following call pancis, it indicates UnimplementedChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_GetOnlineUserIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnlineUserIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetOnlineUserIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_GetOnlineUserIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetOnlineUserIds(ctx, req.(*GetOnlineUserIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetConnInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetConnInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_GetConnInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetConnInfo(ctx, req.(*GetConnInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_NoticeRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).NoticeRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_NoticeRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).NoticeRead(ctx, req.(*NoticeReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_UpdateAdminSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).UpdateAdminSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_UpdateAdminSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).UpdateAdminSetting(ctx, req.(*UpdateAdminSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_BroadcastWaitingUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastWaitingUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).BroadcastWaitingUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_BroadcastWaitingUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).BroadcastWaitingUser(ctx, req.(*BroadcastWaitingUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_BroadcastOnlineAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastOnlineAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).BroadcastOnlineAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_BroadcastOnlineAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).BroadcastOnlineAdmins(ctx, req.(*BroadcastOnlineAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_BroadcastQueueLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastQueueLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).BroadcastQueueLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_BroadcastQueueLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).BroadcastQueueLocation(ctx, req.(*BroadcastQueueLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_NoticeTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).NoticeTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_NoticeTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).NoticeTransfer(ctx, req.(*NoticeTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_NoticeUserOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeUserOnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).NoticeUserOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_NoticeUserOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).NoticeUserOnline(ctx, req.(*NoticeUserOnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_NoticeUserOffline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeUserOfflineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).NoticeUserOffline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_NoticeUserOffline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).NoticeUserOffline(ctx, req.(*NoticeUserOfflineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_NoticeRepeatConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeRepeatConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).NoticeRepeatConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_NoticeRepeatConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).NoticeRepeatConnect(ctx, req.(*NoticeRepeatConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOnlineUserIds",
			Handler:    _Chat_GetOnlineUserIds_Handler,
		},
		{
			MethodName: "GetConnInfo",
			Handler:    _Chat_GetConnInfo_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Chat_SendMessage_Handler,
		},
		{
			MethodName: "NoticeRead",
			Handler:    _Chat_NoticeRead_Handler,
		},
		{
			MethodName: "UpdateAdminSetting",
			Handler:    _Chat_UpdateAdminSetting_Handler,
		},
		{
			MethodName: "BroadcastWaitingUser",
			Handler:    _Chat_BroadcastWaitingUser_Handler,
		},
		{
			MethodName: "BroadcastOnlineAdmins",
			Handler:    _Chat_BroadcastOnlineAdmins_Handler,
		},
		{
			MethodName: "BroadcastQueueLocation",
			Handler:    _Chat_BroadcastQueueLocation_Handler,
		},
		{
			MethodName: "NoticeTransfer",
			Handler:    _Chat_NoticeTransfer_Handler,
		},
		{
			MethodName: "NoticeUserOnline",
			Handler:    _Chat_NoticeUserOnline_Handler,
		},
		{
			MethodName: "NoticeUserOffline",
			Handler:    _Chat_NoticeUserOffline_Handler,
		},
		{
			MethodName: "NoticeRepeatConnect",
			Handler:    _Chat_NoticeRepeatConnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat/v1/chat.proto",
}
