// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

type IChatRelation interface {
	AddUser(adminId, uid int) error
	UpdateUser(adminId int, uid int) error
	RemoveUser(adminId int, uid int) error
	IsUserValid(adminId int, uid int) bool
	IsUserExist(adminId int, uid int) bool
	GetLastChatTime(adminId int, uid int) int64
	RemoveLastChatTime(adminId int, uid int) error
	UpdateLastChatTime(adminId int, uid int) error
	GetActiveCount(adminId int) int
	UpdateLimitTime(adminId int, uid int, duration int64) error
	GetLimitTime(adminId int, uid int) int64
	GetInvalidUsers(adminId int) []int
	GetUsersWithLimitTime(adminId int) ([]int, []int64)
	SetUserAdmin(uid int, adminId int) error
	RemoveUserAdmin(uid int) error
	GetUserValidAdmin(uid int) int
}

var localChatRelation IChatRelation

func ChatRelation() IChatRelation {
	if localChatRelation == nil {
		panic("implement not found for interface IChatRelation, forgot register?")
	}
	return localChatRelation
}

func RegisterChatRelation(i IChatRelation) {
	localChatRelation = i
}
