// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"gf-chat/internal/model"
	"gf-chat/internal/model/entity"
)

type IChatSetting interface {
	GetSubscribeId(customerId int) string
	First(customerId int, name string) *entity.CustomerChatSettings
	DefaultAvatarForm(customerId int) *model.ImageFiled
	GetName(customerId int) string
	GetAvatar(customerId int) string
	GetSmsCode(customerId int) string
	GetIsAutoTransferManual(customerId int) bool
}

var localChatSetting IChatSetting

func ChatSetting() IChatSetting {
	if localChatSetting == nil {
		panic("implement not found for interface IChatSetting, forgot register?")
	}
	return localChatSetting
}

func RegisterChatSetting(i IChatSetting) {
	localChatSetting = i
}
