// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

type IJwt interface {
	CreateToken(uid string, sessionId string) (token string, err error)
	ParseToken(token string) (uid string, sessionId string, err error)
}

var localJwt IJwt

func Jwt() IJwt {
	if localJwt == nil {
		panic("implement not found for interface IJwt, forgot register?")
	}
	return localJwt
}

func RegisterJwt(i IJwt) {
	localJwt = i
}
