// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"gf-chat/internal/model/official"
	"gf-chat/internal/model/relation"
)

type IOfficialMsg interface {
	Chat(admin *relation.CustomerAdmins, offline official.Offline) error
	Send(ctx context.Context, message official.Message) error
}

var localOfficialMsg IOfficialMsg

func OfficialMsg() IOfficialMsg {
	if localOfficialMsg == nil {
		panic("implement not found for interface IOfficialMsg, forgot register?")
	}
	return localOfficialMsg
}

func RegisterOfficialMsg(i IOfficialMsg) {
	localOfficialMsg = i
}
