// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
)

type IRefund interface {
	GetCommittedCount(ctx context.Context, uid int) int
}

var localRefund IRefund

func Refund() IRefund {
	if localRefund == nil {
		panic("implement not found for interface IRefund, forgot register?")
	}
	return localRefund
}

func RegisterRefund(i IRefund) {
	localRefund = i
}
