// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"gf-chat/internal/model/do"
	"gf-chat/internal/model/entity"
)

type ISms interface {
	Send(ctx context.Context, code string, uid int) error
	First(w do.SmsTemplates) *entity.SmsTemplates
	CheckChatSms(model *entity.SmsTemplates) error
	GetValidTemplate(customerId int) []entity.SmsTemplates
}

var localSms ISms

func Sms() ISms {
	if localSms == nil {
		panic("implement not found for interface ISms, forgot register?")
	}
	return localSms
}

func RegisterSms(i ISms) {
	localSms = i
}
