// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"gf-chat/internal/model/do"
	"gf-chat/internal/model/entity"
	"gf-chat/internal/model/relation"
)

type IUser interface {
	GetUsers(ctx context.Context, w any) []*entity.Users
	First(w do.Users) *entity.Users
	FindByToken(token string) (*entity.Users, *entity.UserApps)
	GetRelateStudents(uid int) []relation.Student
	GetStudents(uid int) []entity.Students
	GetSchools(uid int) []entity.Schools
}

var localUser IUser

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
