// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalAdminsDao is internal type for wrapping internal DAO implements.
type internalAdminsDao = *internal.AdminsDao

// adminsDao is the data access object for table admins.
// You can define custom methods on it to extend its functionality as you wish.
type adminsDao struct {
	internalAdminsDao
}

var (
	// Admins is globally public accessible object for table admins operations.
	Admins = adminsDao{
		internal.NewAdminsDao(),
	}
)

// Fill with you ideas below.
