// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalCustomerKitchensDao is internal type for wrapping internal DAO implements.
type internalCustomerKitchensDao = *internal.CustomerKitchensDao

// customerKitchensDao is the data access object for table customer_kitchens.
// You can define custom methods on it to extend its functionality as you wish.
type customerKitchensDao struct {
	internalCustomerKitchensDao
}

var (
	// CustomerKitchens is globally public accessible object for table customer_kitchens operations.
	CustomerKitchens = customerKitchensDao{
		internal.NewCustomerKitchensDao(),
	}
)

// Fill with you ideas below.
