// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalCustomerAdminsDao is internal type for wrapping internal DAO implements.
type internalCustomerAdminsDao = *internal.CustomerAdminsDao

// customerAdminsDao is the data access object for table customer_admins.
// You can define custom methods on it to extend its functionality as you wish.
type customerAdminsDao struct {
	internalCustomerAdminsDao
}

var (
	// CustomerAdmins is globally public accessible object for table customer_admins operations.
	CustomerAdmins = customerAdminsDao{
		internal.NewCustomerAdminsDao(),
	}
)

// Fill with you ideas below.
