// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalCustomerChatSettingsDao is internal type for wrapping internal DAO implements.
type internalCustomerChatSettingsDao = *internal.CustomerChatSettingsDao

// customerChatSettingsDao is the data access object for table customer_chat_settings.
// You can define custom methods on it to extend its functionality as you wish.
type customerChatSettingsDao struct {
	internalCustomerChatSettingsDao
}

var (
	// CustomerChatSettings is globally public accessible object for table customer_chat_settings operations.
	CustomerChatSettings = customerChatSettingsDao{
		internal.NewCustomerChatSettingsDao(),
	}
)

// Fill with you ideas below.
