// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalCustomerChatAutoRulesDao is internal type for wrapping internal DAO implements.
type internalCustomerChatAutoRulesDao = *internal.CustomerChatAutoRulesDao

// customerChatAutoRulesDao is the data access object for table customer_chat_auto_rules.
// You can define custom methods on it to extend its functionality as you wish.
type customerChatAutoRulesDao struct {
	internalCustomerChatAutoRulesDao
}

var (
	// CustomerChatAutoRules is globally public accessible object for table customer_chat_auto_rules operations.
	CustomerChatAutoRules = customerChatAutoRulesDao{
		internal.NewCustomerChatAutoRulesDao(),
	}
)

// Fill with you ideas below.
