// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalCustomerAdminChatSettingsDao is internal type for wrapping internal DAO implements.
type internalCustomerAdminChatSettingsDao = *internal.CustomerAdminChatSettingsDao

// customerAdminChatSettingsDao is the data access object for table customer_admin_chat_settings.
// You can define custom methods on it to extend its functionality as you wish.
type customerAdminChatSettingsDao struct {
	internalCustomerAdminChatSettingsDao
}

var (
	// CustomerAdminChatSettings is globally public accessible object for table customer_admin_chat_settings operations.
	CustomerAdminChatSettings = customerAdminChatSettingsDao{
		internal.NewCustomerAdminChatSettingsDao(),
	}
)

// Fill with you ideas below.
