// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalCustomerChatAutoRuleScenesDao is internal type for wrapping internal DAO implements.
type internalCustomerChatAutoRuleScenesDao = *internal.CustomerChatAutoRuleScenesDao

// customerChatAutoRuleScenesDao is the data access object for table customer_chat_auto_rule_scenes.
// You can define custom methods on it to extend its functionality as you wish.
type customerChatAutoRuleScenesDao struct {
	internalCustomerChatAutoRuleScenesDao
}

var (
	// CustomerChatAutoRuleScenes is globally public accessible object for table customer_chat_auto_rule_scenes operations.
	CustomerChatAutoRuleScenes = customerChatAutoRuleScenesDao{
		internal.NewCustomerChatAutoRuleScenesDao(),
	}
)

// Fill with you ideas below.
