// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalCustomerAdminWechatDao is internal type for wrapping internal DAO implements.
type internalCustomerAdminWechatDao = *internal.CustomerAdminWechatDao

// customerAdminWechatDao is the data access object for table customer_admin_wechat.
// You can define custom methods on it to extend its functionality as you wish.
type customerAdminWechatDao struct {
	internalCustomerAdminWechatDao
}

var (
	// CustomerAdminWechat is globally public accessible object for table customer_admin_wechat operations.
	CustomerAdminWechat = customerAdminWechatDao{
		internal.NewCustomerAdminWechatDao(),
	}
)

// Fill with you ideas below.
