// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalCustomerChatFilesDao is internal type for wrapping internal DAO implements.
type internalCustomerChatFilesDao = *internal.CustomerChatFilesDao

// customerChatFilesDao is the data access object for table customer_chat_files.
// You can define custom methods on it to extend its functionality as you wish.
type customerChatFilesDao struct {
	internalCustomerChatFilesDao
}

var (
	// CustomerChatFiles is globally public accessible object for table customer_chat_files operations.
	CustomerChatFiles = customerChatFilesDao{
		internal.NewCustomerChatFilesDao(),
	}
)

// Fill with you ideas below.
