// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalCustomersDao is internal type for wrapping internal DAO implements.
type internalCustomersDao = *internal.CustomersDao

// customersDao is the data access object for table customers.
// You can define custom methods on it to extend its functionality as you wish.
type customersDao struct {
	internalCustomersDao
}

var (
	// Customers is globally public accessible object for table customers operations.
	Customers = customersDao{
		internal.NewCustomersDao(),
	}
)

// Fill with you ideas below.
