// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalRefundOrdersDao is internal type for wrapping internal DAO implements.
type internalRefundOrdersDao = *internal.RefundOrdersDao

// refundOrdersDao is the data access object for table refund_orders.
// You can define custom methods on it to extend its functionality as you wish.
type refundOrdersDao struct {
	internalRefundOrdersDao
}

var (
	// RefundOrders is globally public accessible object for table refund_orders operations.
	RefundOrders = refundOrdersDao{
		internal.NewRefundOrdersDao(),
	}
)

// Fill with you ideas below.
