// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalStudentsDao is internal type for wrapping internal DAO implements.
type internalStudentsDao = *internal.StudentsDao

// studentsDao is the data access object for table students.
// You can define custom methods on it to extend its functionality as you wish.
type studentsDao struct {
	internalStudentsDao
}

var (
	// Students is globally public accessible object for table students operations.
	Students = studentsDao{
		internal.NewStudentsDao(),
	}
)

// Fill with you ideas below.
