// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalUserAppsDao is internal type for wrapping internal DAO implements.
type internalUserAppsDao = *internal.UserAppsDao

// userAppsDao is the data access object for table user_apps.
// You can define custom methods on it to extend its functionality as you wish.
type userAppsDao struct {
	internalUserAppsDao
}

var (
	// UserApps is globally public accessible object for table user_apps operations.
	UserApps = userAppsDao{
		internal.NewUserAppsDao(),
	}
)

// Fill with you ideas below.
