// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalWeappSubscribeMessagesDao is internal type for wrapping internal DAO implements.
type internalWeappSubscribeMessagesDao = *internal.WeappSubscribeMessagesDao

// weappSubscribeMessagesDao is the data access object for table weapp_subscribe_messages.
// You can define custom methods on it to extend its functionality as you wish.
type weappSubscribeMessagesDao struct {
	internalWeappSubscribeMessagesDao
}

var (
	// WeappSubscribeMessages is globally public accessible object for table weapp_subscribe_messages operations.
	WeappSubscribeMessages = weappSubscribeMessagesDao{
		internal.NewWeappSubscribeMessagesDao(),
	}
)

// Fill with you ideas below.
