// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

type IChatManual interface {
	Add(uid int, gid int) error
	IsIn(uid int, customerId int) bool
	Remove(uid int, customerId int) error
	GetTotalCount(customerId int) int
	GetCountByTime(customerId int, min string, max string) int64
	GetByTime(customerId int, min string, max string) []string
	GetTime(uid int, customerId int) float64
	GetAll(customerId int) []int64
	GetBySource(customerId int, Offset, count int) []int64
}

var localChatManual IChatManual

func ChatManual() IChatManual {
	if localChatManual == nil {
		panic("implement not found for interface IChatManual, forgot register?")
	}
	return localChatManual
}

func RegisterChatManual(i IChatManual) {
	localChatManual = i
}
