// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import "github.com/gogf/gf/v2/os/gtime"

type IChatRelation interface {
	AddUser(adminId, uid uint) error
	UpdateUser(adminId uint, uid uint) error
	RemoveUser(adminId uint, uid uint) error
	IsUserValid(adminId uint, uid uint) bool
	IsUserExist(adminId uint, uid uint) bool
	GetLastChatTime(adminId uint, uid uint) uint
	RemoveLastChatTime(adminId uint, uid uint) error
	UpdateLastChatTime(adminId uint, uid uint) error
	GetActiveCount(adminId uint) uint
	UpdateLimitTime(adminId uint, uid uint, duration int64) error
	GetLimitTime(adminId uint, uid uint) int64
	GetInvalidUsers(adminId uint) []uint
	GetUsersWithLimitTime(adminId uint) ([]uint, []int64)
	SetUserAdmin(uid uint, adminId uint) error
	RemoveUserAdmin(uid uint) error
	GetUserValidAdmin(uid uint) uint
}

var localChatRelation IChatRelation

func ChatRelation() IChatRelation {
	if localChatRelation == nil {
		panic("implement not found for interface IChatRelation, forgot register?")
	}
	return localChatRelation
}

func RegisterChatRelation(i IChatRelation) {
	localChatRelation = i
}
