// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

type IChatManual interface {
	Add(uid uint, gid uint) error
	IsIn(uid uint, customerId uint) bool
	Remove(uid uint, customerId uint) error
	GetTotalCount(customerId uint) uint
	GetCountByTime(customerId uint, min string, max string) uint
	GetByTime(customerId uint, min string, max string) []string
	GetTime(uid uint, customerId uint) float64
	GetAll(customerId uint) []uint
	GetBySource(customerId uint, Offset, count uint) []uint
}

var localChatManual IChatManual

func ChatManual() IChatManual {
	if localChatManual == nil {
		panic("implement not found for interface IChatManual, forgot register?")
	}
	return localChatManual
}

func RegisterChatManual(i IChatManual) {
	localChatManual = i
}
