// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

type IChatNotice interface {
	Set(uid int) error
	IsSet(uid int) bool
	Remove(uid int) bool
}

var localChatNotice IChatNotice

func ChatNotice() IChatNotice {
	if localChatNotice == nil {
		panic("implement not found for interface IChatNotice, forgot register?")
	}
	return localChatNotice
}

func RegisterChatNotice(i IChatNotice) {
	localChatNotice = i
}
