// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Admins is the golang structure for table admins.
type Admins struct {
	Id          uint        `json:"id"          ` //
	Username    string      `json:"username"    ` // 用户名
	Password    string      `json:"password"    ` // 密码
	Phone       string      `json:"phone"       ` // 手机号码
	IsSuper     int         `json:"isSuper"     ` // 是否超级管理员
	IsReset     int         `json:"isReset"     ` // 是否重置密码(0 否 1 是)
	Status      int         `json:"status"      ` // 状态
	ApiToken    string      `json:"apiToken"    ` // 登陆token
	ExpireTime  *gtime.Time `json:"expireTime"  ` // token过期时间
	LastLoginAt *gtime.Time `json:"lastLoginAt" ` // 最后登陆时间
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
	DeletedAt   *gtime.Time `json:"deletedAt"   ` // 删除时间
}
