// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// CustomerChatTransfers is the golang structure for table customer_chat_transfers.
type CustomerChatTransfers struct {
	Id            int       `json:"id"            ` //
	UserId        int       `json:"userId"        ` //
	FromSessionId uint64    `json:"fromSessionId" ` //
	ToSessionId   uint64    `json:"toSessionId"   ` //
	FromAdminId   int       `json:"fromAdminId"   ` //
	ToAdminId     int       `json:"toAdminId"     ` //
	CustomerId    int       `json:"customerId"    ` //
	Remark        string    `json:"remark"        ` //
	CreatedAt     time.Time `json:"createdAt"     ` //
	AcceptedAt    int64     `json:"acceptedAt"    ` //
	CanceledAt    int64     `json:"canceledAt"    ` //
}
