// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// CustomerKitchens is the golang structure for table customer_kitchens.
type CustomerKitchens struct {
	Id         int       `json:"id"         ` //
	CustomerId int       `json:"customerId" ` //
	Name       string    `json:"name"       ` // 名称
	Address    string    `json:"address"    ` // 详细地址
	Province   string    `json:"province"   ` //
	City       string    `json:"city"       ` //
	Country    string    `json:"country"    ` //
	Longitude  float64   `json:"longitude"  ` // 经度
	Latitude   float64   `json:"latitude"   ` // 维度
	CreatedAt  time.Time `json:"createdAt"  ` //
	UpdatedAt  time.Time `json:"updatedAt"  ` //
}
