// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// CustomerChatAutoMessages is the golang structure for table customer_chat_auto_messages.
type CustomerChatAutoMessages struct {
	Id         uint64    `json:"id"         ` //
	Name       string    `json:"name"       ` //
	Type       string    `json:"type"       ` //
	Content    string    `json:"content"    ` //
	CustomerId int       `json:"customerId" ` //
	CreatedAt  time.Time `json:"createdAt"  ` //
	UpdatedAt  time.Time `json:"updatedAt"  ` //
}
