// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// CustomerSettings is the golang structure for table customer_settings.
type CustomerSettings struct {
	Id                     int       `json:"id"                     ` //
	CustomerId             int       `json:"customerId"             ` //
	Module                 string    `json:"module"                 ` // 开启的后台模块,按菜单分
	MaxAdminAmount         int       `json:"maxAdminAmount"         ` // 可创建最大管理员数量
	MaxUserAmount          int       `json:"maxUserAmount"          ` // 最大用户数量
	IsOpenSelect           int       `json:"isOpenSelect"           ` // 是否开启选餐
	NextWeekCloseDay       int       `json:"nextWeekCloseDay"       ` // 下周订单截至星期几(0-6)
	NextWeekCloseTime      time.Time `json:"nextWeekCloseTime"      ` // 下周订单截至时间
	OrderPrepareTime       time.Time `json:"orderPrepareTime"       ` // 次日订单准备时间（订单由已提交=》准备中 那天的变化时间）
	OrderPrepareDays       int       `json:"orderPrepareDays"       ` // 订单准备天数
	OrderFinishTime        time.Time `json:"orderFinishTime"        ` //
	IsOpenMpServer         int       `json:"isOpenMpServer"         ` // 是否开启小程序客服功能
	IsLogMpServerMessage   int       `json:"isLogMpServerMessage"   ` // 是否开启客服消息记录
	SettleDay              int       `json:"settleDay"              ` // 结算时间,T+几
	SettleRate             float64   `json:"settleRate"             ` // 结算费率(千分之几)
	SettleBank             string    `json:"settleBank"             ` // 结算银行
	SettleAccount          string    `json:"settleAccount"          ` // 结算银行账号
	SettleAccountName      string    `json:"settleAccountName"      ` // 结算银行账号开户名
	PaymentMethod          int       `json:"paymentMethod"          ` // 支付方式：1：微信支付
	DefaultMealCover       string    `json:"defaultMealCover"       ` // 默认套餐封面
	AutoTypes              string    `json:"autoTypes"              ` // 自动订餐可选用的套餐类型
	AddOrderType           string    `json:"addOrderType"           ` // 加单类型：正常加单、次日加单
	MaxCloudUserAmount     int       `json:"maxCloudUserAmount"     ` // 可创建最大云数据账号数量
	WeappFooter            string    `json:"weappFooter"            ` // 小程序首页底部说明
	ChatOpen               int       `json:"chatOpen"               ` // 客服系统权限
	NextDayAddTime         time.Time `json:"nextDayAddTime"         ` // 次日加单时间
	IsUserFreezingStudents int       `json:"isUserFreezingStudents" ` // 是否允许用户冻结学生
	IsUserChangeMenu       int       `json:"isUserChangeMenu"       ` // 是否允许客户更换套餐
	IsMaintenance          int       `json:"isMaintenance"          ` // 是否开启维护模式
	IsShowAllergen         int       `json:"isShowAllergen"         ` // 是否允许显示过敏源
	IsNuclein              uint      `json:"isNuclein"              ` // 小程序是否显示员工核酸结果
	IsPicture              uint      `json:"isPicture"              ` // 小程序是否显示员工健康证
	IsAllowAutoSetting     int       `json:"isAllowAutoSetting"     ` // 小程序是否允许用户更改自动订餐（1 是 0 否）
	IsUserCancelStudents   int       `json:"isUserCancelStudents"   ` // 是否允许用户注销学生
	IsFeedback             uint      `json:"isFeedback"             ` // 小程序是否显示反馈意见(1 是 0 否)
	FeedbackNickname       string    `json:"feedbackNickname"       ` // 反馈意见回复昵称
	IsRollbackCancel       int       `json:"isRollbackCancel"       ` // 是否允许用户取消请假
}
