// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// CustomerChatSessions is the golang structure for table customer_chat_sessions.
type CustomerChatSessions struct {
	Id         uint64 `json:"id"         ` //
	UserId     int    `json:"userId"     ` //
	QueriedAt  int64  `json:"queriedAt"  ` //
	AcceptedAt int64  `json:"acceptedAt" ` //
	CanceledAt int64  `json:"canceledAt" ` //
	BrokeAt    int64  `json:"brokeAt"    ` //
	CustomerId int    `json:"customerId" ` //
	AdminId    int    `json:"adminId"    ` //
	Type       int    `json:"type"       ` //
	Rate       int    `json:"rate"       ` //
}
