// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// CustomerChatAutoRuleScenes is the golang structure for table customer_chat_auto_rule_scenes.
type CustomerChatAutoRuleScenes struct {
	Id        int64     `json:"id"        ` //
	Name      string    `json:"name"      ` //
	RuleId    uint64    `json:"ruleId"    ` //
	CreatedAt time.Time `json:"createdAt" ` //
	UpdatedAt time.Time `json:"updatedAt" ` //
}
