// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// CustomerChatAutoRules is the golang structure for table customer_chat_auto_rules.
type CustomerChatAutoRules struct {
	Id         uint64    `json:"id"         ` //
	Name       string    `json:"name"       ` //
	Match      string    `json:"match"      ` //
	MatchType  string    `json:"matchType"  ` //
	ReplyType  string    `json:"replyType"  ` //
	MessageId  uint      `json:"messageId"  ` //
	IsSystem   uint      `json:"isSystem"   ` //
	Sort       uint      `json:"sort"       ` //
	IsOpen     int       `json:"isOpen"     ` //
	CustomerId int       `json:"customerId" ` //
	Count      uint64    `json:"count"      ` //
	CreatedAt  time.Time `json:"createdAt"  ` //
	UpdatedAt  time.Time `json:"updatedAt"  ` //
}
