// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// CustomerAdminChatSettings is the golang structure for table customer_admin_chat_settings.
type CustomerAdminChatSettings struct {
	Id             int64     `json:"id"             ` //
	AdminId        uint      `json:"adminId"        ` //
	Background     string    `json:"background"     ` //
	IsAutoAccept   int       `json:"isAutoAccept"   ` //
	WelcomeContent string    `json:"welcomeContent" ` //
	OfflineContent string    `json:"offlineContent" ` //
	Name           string    `json:"name"           ` //
	LastOnline     time.Time `json:"lastOnline"     ` //
	Avatar         string    `json:"avatar"         ` //
	CreatedAt      time.Time `json:"createdAt"      ` //
	UpdatedAt      time.Time `json:"updatedAt"      ` //
}
