// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// CustomerAdminWechat is the golang structure for table customer_admin_wechat.
type CustomerAdminWechat struct {
	Id             int       `json:"id"             ` //
	AdminId        int       `json:"adminId"        ` //
	OpenId         string    `json:"openId"         ` //
	OfficialOpenId string    `json:"officialOpenId" ` //
	Unionid        string    `json:"unionid"        ` //
	Avatar         string    `json:"avatar"         ` //
	CreatedAt      time.Time `json:"createdAt"      ` //
	UpdatedAt      time.Time `json:"updatedAt"      ` //
	Info           string    `json:"info"           ` //
	IsWechatOnly   int       `json:"isWechatOnly"   ` //
}
