// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// CustomerChatSettings is the golang structure for table customer_chat_settings.
type CustomerChatSettings struct {
	Id          int64     `json:"id"          ` //
	Name        string    `json:"name"        ` //
	Title       string    `json:"title"       ` //
	CustomerId  int64     `json:"customerId"  ` //
	Value       string    `json:"value"       ` //
	Options     string    `json:"options"     ` //
	Type        string    `json:"type"        ` //
	CreatedAt   time.Time `json:"createdAt"   ` //
	UpdatedAt   time.Time `json:"updatedAt"   ` //
	Description string    `json:"description" ` //
}
