// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// MealOrders is the golang structure for table meal_orders.
type MealOrders struct {
	Id                   int64     `json:"id"                   ` //
	CustomerId           int       `json:"customerId"           ` //
	UserId               int       `json:"userId"               ` // 用户id
	StudentId            int       `json:"studentId"            ` // 学生id
	MealId               int       `json:"mealId"               ` // 套餐id
	TermId               int       `json:"termId"               ` // 学期id
	SchoolId             int       `json:"schoolId"             ` // 学校id
	StudentTermBalanceId int       `json:"studentTermBalanceId" ` //
	DispatchDate         time.Time `json:"dispatchDate"         ` // 配送日期
	DispatchGradeId      int       `json:"dispatchGradeId"      ` // 配送年纪
	DispatchClassId      int       `json:"dispatchClassId"      ` // 配送班级
	StudentName          string    `json:"studentName"          ` // 学生姓名
	Status               int       `json:"status"               ` // 状态(10:已提交,20:准备中;30:已完成;40:已取消)
	PayPrice             float64   `json:"payPrice"             ` // 支付金额
	PayType              string    `json:"payType"              ` //
	IsBackend            int       `json:"isBackend"            ` // 是否后台添加订单
	IsAuto               int       `json:"isAuto"               ` // 是否自动产生订单
	CreatedAt            time.Time `json:"createdAt"            ` // 下单时间
	UpdatedAt            time.Time `json:"updatedAt"            ` //
	PreparedAt           time.Time `json:"preparedAt"           ` // 准备时间
	FinishedAt           time.Time `json:"finishedAt"           ` // 完成时间
	CancelAt             time.Time `json:"cancelAt"             ` // 取消时间
	CancelReason         string    `json:"cancelReason"         ` // 取消理由
	IsCanceledByUser     int       `json:"isCanceledByUser"     ` // 是否为用户取消
	OrderTypeId          int       `json:"orderTypeId"          ` // 类型id
	GiftPay              int       `json:"giftPay"              ` // 赠送金额支付
}
