// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// RefundOrders is the golang structure for table refund_orders.
type RefundOrders struct {
	Id                   int       `json:"id"                   ` //
	UserId               int       `json:"userId"               ` //
	CustomerId           int       `json:"customerId"           ` //
	No                   string    `json:"no"                   ` // 退款单号
	TermId               int       `json:"termId"               ` // 学期id
	SchoolId             int       `json:"schoolId"             ` //
	StudentId            int       `json:"studentId"            ` //
	OrderTypeId          int       `json:"orderTypeId"          ` // 订餐类型
	RefundAccount        string    `json:"refundAccount"        ` // 退款帐号
	RefundMoney          float64   `json:"refundMoney"          ` // 退款金额
	TransferFee          float64   `json:"transferFee"          ` // 手续费
	Status               int       `json:"status"               ` // 状态;10:已提交
	CreatedAt            time.Time `json:"createdAt"            ` // 申请时间
	UpdatedAt            time.Time `json:"updatedAt"            ` //
	AgreedAt             time.Time `json:"agreedAt"             ` // 同意时间
	RefundAt             time.Time `json:"refundAt"             ` // 退款时间
	CanceledAt           time.Time `json:"canceledAt"           ` // 取消时间
	RejectedAt           time.Time `json:"rejectedAt"           ` // 拒绝时间
	RechargeId           int       `json:"rechargeId"           ` // 充值单id
	StudentTermBalanceId int       `json:"studentTermBalanceId" ` // 学生学期余额id
	Reason               string    `json:"reason"               ` // 退款理由
	Remark               string    `json:"remark"               ` // 备注
	Params               string    `json:"params"               ` // 退款回调参数
	ErrorMsg             string    `json:"errorMsg"             ` // 批量转账失败时的错误信息
	Type                 string    `json:"type"                 ` // 退款类型,recharge:充值，addition:其他缴费
	RechargeAdditionId   int       `json:"rechargeAdditionId"   ` // 额外充值收费id
}
