// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// Schools is the golang structure for table schools.
type Schools struct {
	Id            int       `json:"id"            ` //
	CustomerId    int       `json:"customerId"    ` //
	Name          string    `json:"name"          ` //
	Longitude     float64   `json:"longitude"     ` //
	Latitude      float64   `json:"latitude"      ` //
	Phone         string    `json:"phone"         ` // 客服电话
	Province      string    `json:"province"      ` //
	City          string    `json:"city"          ` //
	Country       string    `json:"country"       ` //
	DetailAddress string    `json:"detailAddress" ` //
	IsDisabled    int       `json:"isDisabled"    ` // 是否禁用，禁用后前台不可见
	CreatedAt     time.Time `json:"createdAt"     ` //
	UpdatedAt     time.Time `json:"updatedAt"     ` //
	KitchenId     int       `json:"kitchenId"     ` // 关联厨房id
	Sort          int       `json:"sort"          ` //
	IsShow        int       `json:"isShow"        ` // 是否删除，删除后前后台均不可见
	SchoolNo      int       `json:"schoolNo"      ` // 学校编码
	CanChange     int       `json:"canChange"     ` // 是否能更改学校(0 否 1 是)
	PaymentMethod int       `json:"paymentMethod" ` // 支付渠道
}
