// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// SmsTemplates is the golang structure for table sms_templates.
type SmsTemplates struct {
	Id         int       `json:"id"         ` //
	CustomerId int       `json:"customerId" ` //
	Type       int       `json:"type"       ` // 短信类型
	Name       string    `json:"name"       ` // 模板名称，长度为1~30个字符
	Content    string    `json:"content"    ` // 模板内容
	Remark     string    `json:"remark"     ` // 短信模板申请说明
	Status     int       `json:"status"     ` // 状态;0:审核中;1:审核通过;2:审核失败
	Code       string    `json:"code"       ` // 模板code
	Reason     string    `json:"reason"     ` // 审核失败理由
	ApprovedAt time.Time `json:"approvedAt" ` // 通过时间
	RejectedAt time.Time `json:"rejectedAt" ` // 拒绝时间
	CreatedAt  time.Time `json:"createdAt"  ` //
	UpdatedAt  time.Time `json:"updatedAt"  ` //
}
