// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// Students is the golang structure for table students.
type Students struct {
	Id                 int       `json:"id"                 ` //
	CustomerId         int       `json:"customerId"         ` // 客户id
	UserId             int       `json:"userId"             ` // 用户Id
	SchoolId           int       `json:"schoolId"           ` // 学校id
	GradeId            int       `json:"gradeId"            ` // 年纪id
	ClassId            int       `json:"classId"            ` // 班级Id
	EatGradeId         int       `json:"eatGradeId"         ` // 就餐年级
	EatClassId         int       `json:"eatClassId"         ` // 就餐班级
	Name               string    `json:"name"               ` // 名称
	NamePinyin         string    `json:"namePinyin"         ` //
	Sex                string    `json:"sex"                ` // 性别
	CreatedAt          time.Time `json:"createdAt"          ` //
	UpdatedAt          time.Time `json:"updatedAt"          ` //
	IsSpecificRecharge int       `json:"isSpecificRecharge" ` // 开启单独充值,不受学校充值设置影响
	IsSpecificRefund   int       `json:"isSpecificRefund"   ` // 开启单独退款，不受学校退款设置影响
	TypeId             int       `json:"typeId"             ` //
	IsAuto             int       `json:"isAuto"             ` // 是否开启自动订餐
	IsHide             int       `json:"isHide"             ` // 是否在前台隐藏：0显示，1隐藏
	IsFreeze           int       `json:"isFreeze"           ` // 非选餐情况下是否不加单
	IsCancel           int       `json:"isCancel"           ` // 是否注销 0否, 1是
}
