// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// UserApps is the golang structure for table user_apps.
type UserApps struct {
	Id            int       `json:"id"            ` //
	UserId        int       `json:"userId"        ` //
	CustomerAppId int       `json:"customerAppId" ` //
	OpenId        string    `json:"openId"        ` //
	AuthToken     string    `json:"authToken"     ` // 验证token
	Session       string    `json:"session"       ` //
	Type          string    `json:"type"          ` // 类型
	CreatedAt     time.Time `json:"createdAt"     ` //
	UpdatedAt     time.Time `json:"updatedAt"     ` //
}
