// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// WeappSubscribeMessages is the golang structure for table weapp_subscribe_messages.
type WeappSubscribeMessages struct {
	Id          int       `json:"id"          ` //
	TempId      string    `json:"tempId"      ` //
	Example     string    `json:"example"     ` //
	Content     string    `json:"content"     ` //
	KeywordEnum string    `json:"keywordEnum" ` //
	Title       string    `json:"title"       ` //
	Type        string    `json:"type"        ` //
	CustomerId  int       `json:"customerId"  ` //
	CreatedAt   time.Time `json:"createdAt"   ` //
	UpdatedAt   time.Time `json:"updatedAt"   ` //
}
